title: Cameron Brien
email: "[cameron] (at) [brien.ca]"
baseurl: "" # the subpath of your site, e.g. /blog
url: "brien.ca" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  cwebrien
description:  ""
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

show_excerpts: true

